grid = [10, 10, 10]
spacing = 0.1
time_step = 0.01
num_steps = 100
output_interval = 1

[bucket]
radius = 1.5
height = 5.0
lid_speed = 0.05
min_height = 0.5

[[spheres]]
center = [-0.5, 0.0, 0.0]
radius = 0.3
velocity = [0.1, 0.0, 0.0]
material_id = 0

[[spheres]]
center = [0.5, 0.0, 0.0]
radius = 0.3
velocity = [-0.1, 0.0, 0.0]
material_id = 0

# Materials definition
[[materials]]
id = 0
name = "matrix"
material_type = "elastoplastic_damage"
density = 2.7e-9
youngs_modulus = 7.2e4
yield_strength = 5e2
hardening_modulus = 1e4
damage_threshold = 0.3

[[materials]]
id = 1
name = "reinforcement"
material_type = "elastoplastic_damage"
density = 3.2e-9
youngs_modulus = 4.15e5
yield_strength = 1.5e3
hardening_modulus = 1e4
damage_threshold = 0.1

[[interfaces]]
mat_a = 0
mat_b = 1
interface_type = "strong"
bond_strength = 1.0
