grid = [10, 10, 10]
spacing = 0.1
time_step = 0.01
num_steps = 100
output_interval = 1

[[spheres]]
center = [-0.5, 0.0, 0.0]
radius = 0.3
velocity = [1.0, 0.0, 0.0]
material_id = 0

[[spheres]]
center = [0.5, 0.0, 0.0]
radius = 0.3
velocity = [-1.0, 0.0, 0.0]
material_id = 1

# Materials definition
[[materials]]
id = 0
name = "matrix"
material_type = "elastoplastic_damage"
density = 1200.0
youngs_modulus = 7.2e4
yield_strength = 5e2
hardening_modulus = 1e4
damage_threshold = 0.2

[[materials]]
id = 1
name = "reinforcement"
material_type = "elastoplastic_damage"
density = 1200.0
youngs_modulus = 7.2e4
yield_strength = 5e2
hardening_modulus = 1e4
damage_threshold = 0.2

[[interfaces]]
mat_a = 0
mat_b = 1
interface_type = "strong"
bond_strength = 1.0
